# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be7c7f477bd78ce5373310cbf4891aa5bbc40b7bcdae771544ba8adee61372484e33589c3bdcfd4e558d86b60be904a6d2fda7ca8d3a1cc51d3ce1a3134550f7

test:
  secret_key_base: c9554ff7597cfc0054b1b5d3c55c9987f68a835010b1cc9befc87ec17920380f502c41fbce9d82a581b2830e3e3ac33b64dd697c62321603eae2798b6dc07a29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
